### ISSUE TITLE
Hero should be able to display captions

### ISSUE THREAD

**Issue by bjcfuller** [uriweb/uri-component-library#74]
## Issue Type

[] Bug  
[] New Feature  
[X] Enhancement  
    
## Description

Hero should have the ability to display captions.  By default, it should display the WP caption of the image (if it's an image hero).  There should also be support for a `caption` shortcode attribute, which, if set, would override the WP caption.  Setting `caption=''` should disable the caption.

**Comment by bjcfuller** [comment]
@johnpennypacker @scouch87 Y'all think this is still needed?  As of late, we've just been using the theme's [feature caption markup](https://gist.github.com/uriwebcom/8e2d34ed91778e8b077936589a9a5c10#file-css-class-feature-caption-html).  Though, hero captions would ideally integrate with WP captions, as stated above.  Thoughts? 🤔

**Comment by johnpennypacker** [comment]
I think in a perfect world, we'd leverage the [caption] shortcode.  That way, instead of building caption functionality into components, we can wrap components with existing caption functionality.  We may need to customize it a bit with [img_caption_shortcode()](https://developer.wordpress.org/reference/functions/img_caption_shortcode/) to handle HTML.

**Comment by bjcfuller** [comment]
That sounds like a great idea.

**Comment by bjcfuller** [comment]
Fixed in 7a07ba5f85735046a36c371ba39ec59e8d8311c0
